/**
 * Hoja DIURNO — solo posición + nombre (ruta 1).
 * Alta: 17/09/2026 · createdBy: Truqui
 */
export const DIURNO_ROUTE_NAMES: string[] = [
  "EDUARDO",
  "EDINSON",
  "CONSE",
  "VICTOR",
  "DORIS",
  "NORA",
  "MARIA NORA",
  "JUAN CARLOS",
  "CECILIA",
  "COCO",
  "NELSON JEFE",
  "EUSEBIO",
  "RONAL PEZ",
  "JOSE PEZ",
  "PACHO PEZ",
  "ALEJO",
  "ALEJO (ANGE)",
  "EDUARDO P",
  "PROFE",
  "BADER",
  "BADER ANGE",
  "ANTONY",
  "FELIX",
  "ERICK",
  "ERICK ANGE",
  "LINSY",
  "CESAR",
  "ROSARIO (ANGE)",
  "JOSE MAN",
  "DANIEL",
  "YURMELY",
  "JUANCHO",
  "ALEX CAFE",
  "FERMA",
  "PAOLA",
  "JOSE CANDADO",
  "CARLOS RELOJ",
  "HERNAN HIJO",
  "MANUEL",
  "ENRIQUE",
  "DAIRO",
  "OMAR",
  "JOSE OMAR",
  "SABALETA OMAR",
  "DARY AMOR",
  "RACHI",
  "SADY",
  "CELINA",
  "JUAN CARLOS",
  "H. JUAN CARLOS",
  "MAYE",
  "KAILANDY",
  "JOSE VIDE",
  "FLACA COMIDA",
  "JHON FLACA",
  "RODOLFO JUGO",
  "JULIO 2",
  "MAURICIO",
  "KARINA",
  "DAGO KARINA",
  "MARIBEL",
  "JOEL ANGE",
  "LUIS OSCAR",
  "FERDERMAN",
  "BORIS",
  "JUAN",
  "YAIRA",
  "LEIDER",
  "DAXONY",
  "CARLOS CERVEZA",
  "VIVIANA",
  "JOHANA MANDELA",
  "JHON MANDELA",
  "NEILA",
  "JENNIFER MANDELA",
  "RAFA",
  "Roberto",
  "Nelson JI",
  "Primo Nelson",
  "Elkin",
  "Guzman",
];

export const DIURNO_ALTA = "17/09/2026";
export const DIURNO_CREATED_BY = "Truqui";
export const DIURNO_ROUTE = "1";
/** Refs COD-18… para no chocar con el filtro de paquete (COD-0…17). */
export const DIURNO_REF_START = 18;

/** Clientes sagrados de la hoja: solo posición + nombre (sin datos privados). */
export function buildDiurnoRoute1Clients() {
  return DIURNO_ROUTE_NAMES.map((name, index) => ({
    ref: `COD-${DIURNO_REF_START + index}`,
    alta: DIURNO_ALTA,
    name,
    lastName: "",
    nickname: "",
    document: "",
    city: "",
    barrio: "",
    route: DIURNO_ROUTE,
    routeOrder: index + 1,
    email: "",
    phone: "",
    address: "",
    notes: "DIURNO",
    total: 0,
    pending: 0,
    status: "Activo",
    kind: "ok" as const,
    createdBy: DIURNO_CREATED_BY,
    awaitingLoan: true,
    profilePending: true,
  }));
}
